### ISSUE TITLE
replace 1067 query with random from top 2014

### ISSUE THREAD

**Issue by dariaphoebe** [dariaphoebe/cd1025-player#1]
http://cd1025.com/about/playlists/history's #content-main can be parsed taking tbody and then choosing a random tuple from it

**Comment by mtlevine0** [comment]
Great idea.  Takes care of that dirty little secret that it wasn't truly cd1025 100% of the time.

**Comment by dariaphoebe** [comment]
function queryCD1025hist(){
        var j = Math.floor((Math.random() \* 2013)+1)
        $.ajax({
            type: "GET",
            url: "http://www.cd1025.com/about/playlists/history",
            success: function(data){
                var wholelist = $(data).find("#content-main").find('tr').eq(j);

```
         var artistNow = $(wholelist).children('td').eq(1).text();
         var songNow = $(wholelist).children('td').eq(2).text();
         console.log(artistNow + " - " + songNow);
         queryYoutube(artistNow, songNow);
         }
     });
```

}

**Comment by dariaphoebe** [comment]
pushed as https://github.com/dbrashear/cd1025-player/tree/dbrashear-top2014-and-ios
